CREATE TABLE internal
(
SL_NO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
REGISTER_NO VARCHAR(10),
NAME VARCHAR(300),
SUBJECT_CODE VARCHAR(255),
SEMESTER INT,
DEPARTMENT VARCHAR(255),
TEST1 INT,
ATTENDANCE1 INT,
TEST2 INT,
ATTENDANCE2 INT,
TEST3 INT,
ATTENDANCE3 INT,
ASSIGNMENT INT,
EXTRA_TEST1 INT,
EXTRA_TEST2 INT,
TOTAL INT
)





CREATE TABLE external
(
SL_NO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
REGISTER_NO VARCHAR(10),
NAME VARCHAR(300),
SUBJECT_CODE VARCHAR(255),
SEMESTER INT,
DEPARTMENT VARCHAR(255),
INTERNAL INT,
EXTERNAL INT,
TOTAL INT,
GRADE VARCHAR(1) NOT NULL
)


